name: Validate JSON

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Validate JSON
        uses: OrRosenblatt/validate-json-action@0.1.0
        with:
          schema: ./schema.json
          json: ./data.json
